[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "indextts"
version = "0.1.4"
description = "An Industrial-Level Controllable and Efficient Zero-Shot Text-To-Speech System"
authors = [
    {name = "Index SpeechTeam", email = "xuanwu@bilibili.com"}
]
readme = "README.md"
requires-python = "==3.10.*"
license = {text = "Apache-2.0"}
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "accelerate==0.25.0",
    "cn2an==0.5.22",
    "cython==3.0.7",
    "ffmpeg-python==0.2.0",
    "g2p-en==2.1.0",
    "gradio==5.32.0",
    "jieba==0.42.1",
    "keras==2.9.0",
    "librosa>=0.11.0",
    "matplotlib==3.8.2",
    "numba==0.58.1",
    "numpy==1.26.2",
    "omegaconf>=2.3.0",
    "opencv-python==4.9.0.80",
    "pandas==2.1.3",
    "sentencepiece>=0.2.0",
    "tensorboard==2.9.1",
    "tokenizers==0.15.0",
    "tqdm>=4.67.1",
    "transformers==4.36.2",
    "vocos==0.1.0",
    "wetext>=0.0.4 ; sys_platform == 'darwin'",
    "wetextprocessing>=1.0.4.1 ; platform_machine != 'Darwin'",
]

[project.optional-dependencies]
webui = ["gradio"]
darwin = ["wetext"]
non-darwin = ["WeTextProcessing"]

[project.scripts]
indextts = "indextts.cli:main"

[tool.uv]
requirements-file = "requirements.txt"
